install.packages("Matrix")
remotes::install_version("Seurat", version = "3.2.2")
install.packages("ggplot2")
install.packages("ggsci")
install.packages("dplyr")
install.packages("pheatmap")
install.packages("RColorBrewer")
